services:
  budget-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    env_file:
      - .env
    volumes:
      - budget-data:/data

  budget-migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    env_file:
      - .env
    volumes:
      - budget-data:/data
    command: ["bun", "run", "db:deploy"]

volumes:
  budget-data:
