services:
  budget-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/data/budget.sqlite
    volumes:
      - budget-data:/data

  budget-migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/data/budget.sqlite
    volumes:
      - budget-data:/data
    command: ["pnpm", "run", "db:deploy"]

volumes:
  budget-data:
