services:
  budget-app:
    build:
      context: .
      dockerfile: src/main/docker/java.dockerfile
    environment:
      LANG: de_DE.UTF-8
      SPRING_R2DBC_URL: "r2dbc:h2:file:////data/budget"
      SPRING_FLYWAY_URL: "jdbc:h2:/data/budget"
    volumes:
      - budget-data:/data
    ports:
      - 8080:8080

volumes:
  budget-data: