spring:
  sql:
    init:
      encoding: UTF-8
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:h2:file:///./budget
    username: sa
    password:
  flyway:
    url: jdbc:h2:./budget
    locations: classpath:db/h2/migration

#logging:
#  level:
#    io.r2dbc.postgresql.QUERY: DEBUG # for queries
#    io.r2dbc.postgresql.PARAM: DEBUG # for parameters